Error creating comment: PrismaClientKnownRequestError: 
Invalid `prisma.comment.create()` invocation:


An operation failed because it depends on one or more records that were required but not found. No 'User' record(s) (needed to inline the relation on 'Comment' record(s)) was found for a nested connect on one-to-many relation 'CommentToUser'.
    at $n.handleRequestError (D:\projects\react-challenge\node_modules\@prisma\client\runtime\library.js:121:7315)
    at $n.handleAndLogRequestError (D:\projects\react-challenge\node_modules\@prisma\client\runtime\library.js:121:6623)
    at $n.request (D:\projects\react-challenge\node_modules\@prisma\client\runtime\library.js:121:6307)
    at async l (D:\projects\react-challenge\node_modules\@prisma\client\runtime\library.js:130:9633)
    at async POST (webpack-internal:///(rsc)/./app/api/comments/route.ts:27:25)
    at async D:\projects\react-challenge\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55778
    at async eO.execute (D:\projects\react-challenge\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
    at async eO.handle (D:\projects\react-challenge\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57112)
    at async doRender (D:\projects\react-challenge\node_modules\next\dist\server\base-server.js:1345:42)
    at async cacheEntry.responseCache.get.routeKind (D:\projects\react-challenge\node_modules\next\dist\server\base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (D:\projects\react-challenge\node_modules\next\dist\server\base-server.js:1475:28)
    at async DevServer.renderPageComponent (D:\projects\react-challenge\node_modules\next\dist\server\base-server.js:1901:24)
    at async DevServer.renderToResponseImpl (D:\projects\react-challenge\node_modules\next\dist\server\base-server.js:1939:32)
    at async DevServer.pipeImpl (D:\projects\react-challenge\node_modules\next\dist\server\base-server.js:914:25)
    at async NextNodeServer.handleCatchallRenderRequest (D:\projects\react-challenge\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (D:\projects\react-challenge\node_modules\next\dist\server\base-server.js:810:17)
    at async D:\projects\react-challenge\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\projects\react-challenge\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (D:\projects\react-challenge\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (D:\projects\react-challenge\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (D:\projects\react-challenge\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (D:\projects\react-challenge\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (D:\projects\react-challenge\node_modules\next\dist\server\lib\start-server.js:141:13) {
  code: 'P2025',
  clientVersion: '5.22.0',
  meta: {
    modelName: 'Comment',
    cause: "No 'User' record(s) (needed to inline the relation on 'Comment' record(s)) was found for a nested connect on one-to-many relation 'CommentToUser'."
  }
}


- users should be added to the database after logging in 